twig:
  file_name_pattern: "*.twig"
  form_themes: ['bootstrap_5_layout.html.twig']
  globals:
    appName: "%appName%"
  paths:
      '%kernel.project_dir%/vendor/bnine/filesbundle/templates': BnineFilesBundle

when@test:
  twig:
    strict_variables: true
