parameters:
  appEnv: "%env(resolve:APP_ENV)%"
  appSecret: "%env(resolve:APP_SECRET)%"
  appName: "%env(resolve:APP_NAME)%"
  appNoreply: "%env(resolve:APP_NOREPLY)%"
  appAdmin: "%env(resolve:APP_ADMIN)%"
  modeAuth: "%env(resolve:MODE_AUTH)%"
  casHost: "%env(resolve:CAS_HOST)%"
  casPort: "%env(resolve:CAS_PORT)%"
  casPath: "%env(resolve:CAS_PATH)%"
  casUsername: "%env(resolve:CAS_USERNAME)%"
  casMail: "%env(resolve:CAS_MAIL)%"
  casLastname: "%env(resolve:CAS_LASTNAME)%"
  casFirstname: "%env(resolve:CAS_FIRSTNAME)%"
  etherpadUrl: "%env(resolve:ETHERPAD_URL)%"
  etherpadInternalUrl: "%env(resolve:ETHERPAD_INTERNALURL)%"
  etherpadApiKey: "%env(resolve:ETHERPAD_APIKEY)%"
  webdavActivate: "%env(resolve:WEBDAV_ACTIVATE)%"
  webdavUrl: "%env(resolve:WEBDAV_URL)%"
  webdavUser: "%env(resolve:WEBDAV_USER)%"
  webdavPassword: "%env(resolve:WEBDAV_PASSWORD)%"

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Security\DynamicAuthenticator:
        arguments:
            $modeAuth: '%env(MODE_AUTH)%'